// IW9 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

asm_register()
{
    if ( !isdefined( anim.asmfuncs ) )
        anim.asmfuncs = [];

    if ( isdefined( anim.asmfuncs["corner_cover_lean_shoot"] ) )
        return;

    anim.asmfuncs["corner_cover_lean_shoot"] = [];
    anim.asmfuncs["corner_cover_lean_shoot"][0] = ::autogenfunc_0;
}

autogenfunc_0( asmname, statename, _id_F2B19B25D457C2A6, params )
{
    return isdefined( self.node ) && self.node.type == "Cover Left";
}
